spring: 
    profiles: 
        active: 
           - dev
---
spring: 
    profiles: dev
    application: 
        name:   microservicecloud-config-shr-dev

---
spring: 
    profiles: test
    application: 
        name:   microservicecloud-config-shr-test
